version: "3"

services:
  mc:
    image: itzg/minecraft-server:java17
    container_name: mc
    ports:
      - "25565:25565"
    environment:
      EULA: "TRUE"
      TZ: "Asia/Shanghai"
      MEMORY: "1G"
      MOTD: "minecraft base 1.19.4"
      DIFFICULTY: "hard"
      MAX_PLAYERS: 5
      ANNOUNCE_PLAYER_ACHIEVEMENTS: "true"
    tty: true
    stdin_open: true
    restart: unless-stopped
    volumes:
      - ./minecraft:/data

  ftb-skies:
    image: itzg/minecraft-server:java17
    container_name: ftb-skies
    ports:
      - "25566:25565"
    environment:
      EULA: "TRUE"
      TZ: "Asia/Shanghai"
      TYPE: "FTBA"
      MEMORY: "5G"
      FTB_MODPACK_ID: 103
      FTB_MODPACK_VERSION_ID: 6458
      MOTD: "FTB Skies"
      DIFFICULTY: "hard"
      MAX_PLAYERS: 5
      ANNOUNCE_PLAYER_ACHIEVEMENTS: "true"
      ALLOW_FLIGHT: "TRUE"
    tty: true
    stdin_open: true
    restart: unless-stopped
    volumes:
      - ./ftb-skies:/data