version: "3"

services:
  mc:
    image: itzg/minecraft-server:java17
    container_name: mc
    ports:
      - "25565:25565"
    environment:
      EULA: "TRUE"
      TZ: "Asia/Shanghai"
      SERVER_NAME: "最新原版"
    tty: true
    stdin_open: true
    restart: unless-stopped
    volumes:
      - ./minecraft:/data

  ftb-skies:
    image: itzg/minecraft-server:java17
    container_name: ftb-skies
    ports:
      - "25566:25565"
    environment:
      EULA: "TRUE"
      TZ: "Asia/Shanghai"
      TYPE: "FTBA"
      MEMORY: "5G"
      FTB_MODPACK_ID: 103
      SERVER_NAME: "FTB Skies"
    tty: true
    stdin_open: true
    restart: unless-stopped
    volumes:
      - ./ftb-skies:/data